GoldenGames.Web/GoldenGames/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoldenGames.Data;
using GoldenGames.Models;
using Microsoft.AspNetCore.Authorization;

namespace GoldenGames.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return View(await _context.Categoria.ToListAsync());
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Categorium categorium)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categorium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categorium);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categoria == null)
            {
                return NotFound();
            }

            var categorium = await _context.Categoria.FindAsync(id);
            if (categorium == null)
            {
                return NotFound();
            }
            return View(categorium);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Categorium categorium)
        {
            if (id != categorium.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categorium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriumExists(categorium.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categorium);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categoria == null)
            {
                return NotFound();
            }

            var categorium = await _context.Categoria
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorium == null)
            {
                return NotFound();
            }

            return View(categorium);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categoria == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categoria'  is null.");
            }
            var categorium = await _context.Categoria.FindAsync(id);
            if (categorium != null)
            {
                _context.Categoria.Remove(categorium);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriumExists(int id)
        {
          return _context.Categoria.Any(e => e.Id == id);
        }
    }
}

GoldenGames.Web/GoldenGames/Controllers/ConsolasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoldenGames.Data;
using GoldenGames.Models;
using Microsoft.AspNetCore.Authorization;

namespace GoldenGames.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConsolasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConsolasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Consolas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Consolas.ToListAsync());
        }


        // GET: Consolas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Consolas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Consola consola)
        {
            if (ModelState.IsValid)
            {
                _context.Add(consola);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(consola);
        }

        // GET: Consolas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Consolas == null)
            {
                return NotFound();
            }

            var consola = await _context.Consolas.FindAsync(id);
            if (consola == null)
            {
                return NotFound();
            }
            return View(consola);
        }

        // POST: Consolas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Consola consola)
        {
            if (id != consola.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consola);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsolaExists(consola.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(consola);
        }

        // GET: Consolas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Consolas == null)
            {
                return NotFound();
            }

            var consola = await _context.Consolas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consola == null)
            {
                return NotFound();
            }

            return View(consola);
        }

        // POST: Consolas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Consolas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Consolas'  is null.");
            }
            var consola = await _context.Consolas.FindAsync(id);
            if (consola != null)
            {
                _context.Consolas.Remove(consola);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConsolaExists(int id)
        {
          return _context.Consolas.Any(e => e.Id == id);
        }
    }
}

GoldenGames.Web/GoldenGames/Controllers/FavCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoldenGames.Data;
using GoldenGames.Models;
using Microsoft.AspNetCore.Identity;
using System.Drawing;
using System.Security.Claims;
using GoldenGames.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Authorization;

namespace GoldenGames.Controllers
{
    [Authorize]
    public class FavCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;
        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public FavCategoriesController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                ModelState.AddModelError("", "Utilizador não encontrado");
                return RedirectToAction("Index", "Home");
            }

            var favCategories = await _context.FavCategories
                .Include(f => f.IdCategoriaNavigation)
                .Where(f => f.UserId == userId)
                .ToListAsync();

            ViewData["categories"] = _context.Categoria.ToList();

            return View(favCategories);
        }


        [HttpPost]
        public async Task<IActionResult> AddCategory(string SelectedCategory)
        {
   

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                ModelState.AddModelError("", "Utilizador não encontrado");
                return RedirectToAction("Index", "Home");
            }

            var selectedCategory = _context.Categoria.FirstOrDefault(c => c.Nome == SelectedCategory);
            if (selectedCategory == null)
            {
                ModelState.AddModelError("", "Categoria selecionada não encontrada");
                return RedirectToAction("Index");
            }

            var existingFavCategory = await _context.FavCategories.FirstOrDefaultAsync( f => f.UserId == userId && f.IdCategoria == selectedCategory.Id);
            if (existingFavCategory != null)
            {
                ModelState.AddModelError("", "Categoria já adicionada como favorita");
                return RedirectToAction("Index");
            }

            var favCategory = new FavCategories 
            { 
                UserId = userId, 
                IdCategoria = selectedCategory.Id, 
                IdCategoriaNavigation = selectedCategory
            };

            _context.FavCategories.Add(favCategory);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                ModelState.AddModelError("", "Utilizador não encontrado");
                return RedirectToAction("Index", "Home");
            }

            var favCategory = await _context.FavCategories
                .FirstOrDefaultAsync(z => z.IdCategoria == id && z.UserId == userId);

            if (favCategory == null)
            {
                return NotFound();
            }

            _context.FavCategories.Remove(favCategory);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


    }   
}

GoldenGames.Web/GoldenGames/Controllers/RolesController.cs
using GoldenGames.Data;
using GoldenGames.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace GoldenGames.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly ILogger<RolesController> _logger;
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(ILogger<RolesController> logger,
            ApplicationDbContext dbContext,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _logger = logger;
            _dbContext = dbContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        public IActionResult ChangeRole()
        {
          
            var userRoleViewModel = new UserRolesViewModel { };
            ViewData["roles"] = _roleManager.Roles.ToList();
            return View("ChangeRole", userRoleViewModel);
          
        }

        //Vai ser usada pelos admins para mudar roles, depois é necessário adicionar authorization aqui
        //Apenas ADMINS pode aceder a toda esta pagina, esta definido em cima do RollesController
        public async Task<ActionResult> GetUser(string findUser)
        {
            ViewData["roles"] = _roleManager.Roles.ToList();
            var user = await _userManager.FindByNameAsync(findUser);

            if (user != null)
            {
                
                var roles = await _userManager.GetRolesAsync(user);
                var userRole = roles.FirstOrDefault();

                var userRoleViewModel = new UserRolesViewModel
                {
                    User = user.UserName,
                    UserRole = userRole
                };

             

                return View("ChangeRole", userRoleViewModel);
            }
            else
            {

                ModelState.AddModelError("", "Utilizador não encontrado");
                return View("ChangeRole");

            }
        }
        [HttpPost]
        public async Task<IActionResult> ChangeRole(string findUser, string selectedRole)
        {
            if (string.IsNullOrEmpty(findUser))
            {
                return View("ChangeRole");
            }
            ViewData["roles"] = _roleManager.Roles.ToList();

            var user = await _userManager.FindByNameAsync(findUser);
            var roles = await _userManager.GetRolesAsync(user);
            var userRole = roles.FirstOrDefault();
            _userManager.RemoveFromRoleAsync(user, userRole).Wait();
            _userManager.AddToRoleAsync(user, selectedRole).Wait();


            var rolefinal = await _userManager.GetRolesAsync(user);
            var userRolefinal = rolefinal.FirstOrDefault();


            var userRoleViewModel = new UserRolesViewModel
            {
                User = user.UserName,
                UserRole = userRolefinal
            };
            return View("ChangeRole", userRoleViewModel);
        }
    }
}

GoldenGames.Web/GoldenGames/Views/Shared/Menu.cshtml
<div class="category-platform-div">
    <div id='_element' class="category-div" height="200" width="200">
        <h2 class="category-div-name">Categories</h2>
        <div>
            <input type="checkbox" id="list-01" name="categorias" value="açao">
            <label style="color:white" for="coding">Ação</label>
        </div>
        <div>
            <input type="checkbox" id="list-02" name="categorias" value="aventura">
            <label style="color:white" for="coding">Aventura</label>
        </div>
        <div>
            <input type="checkbox" id="list-03" name="categorias" value="desporto">
            <label style="color:white" for="coding">Desporto</label>
        </div>
        <div>
            <input type="checkbox" id="list-04" name="categorias" value="Fantasia">
            <label style="color:white" for="coding">Fantasia</label>
        </div>
        <div>
            <input type="checkbox" id="list-05" name="categorias" value="mmorpg">
            <label style="color:white" for="coding">MMORPG</label>
        </div>
        <div>
            <input type="checkbox" id="list-06" name="categorias" value="moba">
            <label style="color:white" for="coding">MOBA</label>
        </div>
        <div>
            <input type="checkbox" id="list-07" name="categorias" value="terror">
            <label style="color:white" for="coding">Terror</label>
        </div>
        <div>
            <input type="checkbox" id="list-08" name="categorias" value="multiplayer">
            <label style="color:white" for="coding">MultiPlayer</label>
        </div>
        <div>
            <input type="checkbox" id="list-09" name="categorias" value="singleplayer">
            <label style="color:white" for="coding">SinglePlayer</label>
        </div>
        <div>
            <input type="checkbox" id="list-10" name="categorias" value="tabuleiro">
            <label style="color:white" for="coding">Tabuleiro</label>
        </div>
    </div>
    <div id='platform-element' class="category-div" height="200" width="200">
        <h2 class="category-div-name">Platforms</h2>
        <div>
            <input type="checkbox" id="list-01" name="plataformas" value="xbox">
            <label for="coding">XBox</label>
        </div>
        <div>
            <input type="checkbox" id="list-02" name="plataformas" value="playstation">
            <label for="coding">Playstation</label>
        </div>
        <div>
            <input type="checkbox" id="list-03" name="plataformas" value="wii">
            <label for="coding">Wii</label>
        </div>
        <div>
             <input type="checkbox" id="list-05" name="plataformas" value="nintendoswitch">
            <label for="coding">Nintendo Switch</label>
        </div>
    </div>
    <div class="price-search">
        <h2 class="price-seach-name">Price</h2>
        <input id="low-price" type="number" minlength="1" maxlength="3">
    </div>
    <div>
        <button type="submit">Pesquisar</button>
    </div>
</div>

GoldenGames.Web/GoldenGames/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoldenGames</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GoldenGames.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-GGbackground border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoldenGames</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Lista de Jogos</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="FavCategories" asp-action="Index">Favoritos</a>
                            </li>
                            @if (User.IsInRole("Funcionario") || User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="InfoProduct" asp-action="Create">Criar Produto</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Consolas" asp-action="Index">Gerir Consolas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="ChangeRole">Gerir Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Gerir Categorias</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GoldenGames.Web/GoldenGames/Views/Shared/_PartialJogos.cshtml
@using GoldenGames.Areas.Admin.ViewModels
@using GoldenGames.Models

﻿@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@model IList<Jogo>
@{
    //  Casting
    var jogos = (List<Jogo>)ViewData["Jogos"];
}


<!--Stand Alone games-->
<div class="vrdstand">
        <!--Se o utilizador carregar vai ser redirecionado para o InfoProduct Details-->
        @foreach(var game in Model.ToList())
        {
            <div>
                <a asp-area="" asp-controller="InfoProduct" asp-action="Index" asp-route-id="@game.Id">
                    <img class="game-images border border-warning rounded-4" src="data:image/*;base64,@(Convert.ToBase64String(game.Imagem))" style="position:relative; right:20px; height:250px; width:250px" />
                </a>

                <label class="game-label" style="font-size:20px">@game.Nome</label>
                <label class="category-label" style="font-size:20px">@game.IdCategoriaNavigation.Nome</label>
                @if (SignInManager.IsSignedIn(User))
                {
                <a asp-controller="Cart" asp-action="AddToCart" asp-route-gameid= "@game.Id" style="position:relative; left:90px; top:-20px" class="btn btn-outline-warning">Buy</a>
                }
            </div>
           
        }
</div>