GoldenGames.Web/GoldenGames/Controllers/InfoProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoldenGames.Data;
using GoldenGames.Models;
using Microsoft.AspNetCore.Identity;
using GoldenGames.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using SendGrid.Helpers.Mail;
using Bogus;
using System.Diagnostics.Metrics;

namespace GoldenGames.Controllers
{
    public class InfoProductController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;
        private Task<IdentityUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        public InfoProductController(ApplicationDbContext dbContext, 
            UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _emailSender = emailSender;

        }

        // GET: InfoProduct
        //A página Index tem como propósito mostrar o resultado do jogo que o utilizador deu click
        [AllowAnonymous]
        public async Task<IActionResult> Index(int Id)
        {
            //Vamos pesquisar a base de dados o jogo escolhido atrvés do Id passado
            var gameResult = await _dbContext.Jogos.FirstOrDefaultAsync(x => x.Id == Id);

            var game = await _dbContext.Jogos
                .Include(g => g.Reviews)
                .FirstOrDefaultAsync(g => g.Id == Id);

            if (gameResult == null)
            {
                return NotFound();
            }
            else
            {
                List<Jogo> jogo = new List<Jogo>();
                
                //Vamos criar um objeto que contenha toda a informação relacionada com o jogo
                //Para enviarmos essa informação para a view e apresentá-la
                Jogo _jogo = new Jogo
                {
                    Id = gameResult.Id,
                    Nome = gameResult.Nome,
                    Descricao = gameResult.Descricao,
                    Produtora = gameResult.Produtora,
                    Preco = gameResult.Preco,
                    Imagem = gameResult.Imagem
                };
                jogo.Add(_jogo);

                //O nosso IdConsolaNavigation n esta a funcionar corretamente, estou a fazer alguma merda de errado
                //Pelo motivo de avançar dado o curto espaço de tempo vou ter de deixar assim
                string nomeCategoria = _dbContext.Categoria.FirstOrDefaultAsync(x => x.Id == gameResult.IdCategoria).Result.Nome;
                string nomeConsola = _dbContext.Consolas.FirstOrDefaultAsync(x => x.Id == gameResult.IdConsola).Result.Nome;

                ViewBag.Imagem = gameResult.Imagem;
                ViewBag.NomeConsola = nomeConsola;
                ViewBag.NomeCategoria = nomeCategoria;

                ViewData["Jogo"] = jogo;
                ViewData["Reviews"] = game.Reviews;
            }
            return View(gameResult);
        }

        // GET: InfoProduct/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _dbContext.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _dbContext.Jogos
                .FirstOrDefaultAsync(m => m.Id == id);

            if (jogo == null)
            {
                return NotFound();
            }

            return View(jogo);
        }

        // GET: InfoProduct/Create
        [Authorize(Roles = "Admin, Funcionario")]
        public IActionResult Create()
        {
            //Criar a nossa lista com todo o conteúdo presente na base de dados
            IList<Categorium> categorias = _dbContext.Categoria.ToList();
            IList<Consola> consolas = _dbContext.Consolas.ToList();

            //Passar esse conteudo para a view
            ViewData["Categorias"] = categorias;
            ViewData["Consolas"] = consolas;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Funcionario")]
        public async Task<IActionResult> Create(JogoViewModel jogoViewModel)
        {
            byte[] imageArray;

            if (Request.Form.Files.Count > 0)
            {
                //Vamos adicionar a imagem do jogo a DB
                IFormFile file = Request.Form.Files.FirstOrDefault();
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    imageArray = dataStream.ToArray();

                }


                if (ModelState.IsValid)
                {
                    //Vai buscar o utilizador logged in, neste preciso momento
                    var user = await GetCurrentUserAsync();

                    //Vamos verificar se existe na BD a nova entrada
                    var validacaoNome = await _dbContext.Jogos.FirstOrDefaultAsync(x => x.Nome.Equals(jogoViewModel.Nome));

                    //Se não exsite nenhuma entrada
                    if (validacaoNome == null)
                    {
                        /*Estou a colocar isto por preguiça não encontro uma resposta para o meu 
                         porque de me estar a adicionar um elemento sem lhe atribuir um Id automaticamente*/
                        int count = _dbContext.Jogos.Count();

                        //Criar o jogo com os parâmetros inseridos
                        Jogo novoJogo = new Jogo()
                        {

                            Nome = jogoViewModel.Nome,
                            Descricao = jogoViewModel.Descricao,
                            Produtora = jogoViewModel.Produtora,
                            IdCategoria = jogoViewModel.IdCategoria,
                            IdConsola = jogoViewModel.IdConsola,
                            Preco = jogoViewModel.Preco,    
                            Imagem = imageArray,
                        };

                        var result = await _dbContext.Jogos.AddAsync(novoJogo);
                        _dbContext.SaveChanges();

                        /// Fazer o mesmo aqui pk esta acontecer the same bullshit /
                        int countRJ = _dbContext.RegistoJogos.Count();

                        //Registar o jogo agarrado ao Id do utilizador para sabermos quem o adicionou
                        RegistoJogo registoJogo = new RegistoJogo()
                        {

                            IdJogo = novoJogo.Id,
                            IdUtilizador = user.Id
                        };

                        var resultRJ = _dbContext.RegistoJogos.AddAsync(registoJogo);
                        _dbContext.SaveChanges();

                        var users = _dbContext.FavCategories
                            .Where(f => f.IdCategoria == jogoViewModel.IdCategoria)
                            .Select(f => f.IdUtilizadorNavigation)
                            .ToList();

                        var categoria = _dbContext.Categoria
                            .FirstOrDefault(m => m.Id == jogoViewModel.IdCategoria);

                        foreach (var userToEmail in users)
                        {
                            await _emailSender.SendEmailAsync(
                                userToEmail.Email,
                                "Novo jogo disponível",
                                $"Olá {userToEmail.UserName},<br> Um novo jogo da categoria {categoria.Nome} " +
                                $"acabou de ser adicionado à nossa loja." +
                                $" <br> Aproveite para dar uma vista de olhos!");
                        }
                        //Mensagem de sucesso
                        TempData["Success"] = "Jogo adicionado";
                        return RedirectToAction();

                    }
                    else
                    {
                        ModelState.AddModelError("Nome", "Nome introduzido já existe. Insira um nome diferente.");
                    }
                }
                else
                {
                    //Isto não está bem como apresentaçao de erro
                    ModelState.AddModelError("Error", "Model State Not Valid");
                }

            }
            else
            {
                ModelState.AddModelError("Imagem", "Insira uma imagem de capa para o jogo.");
            }

            return RedirectToAction();
        }

        // GET: InfoProduct/Edit/5
        [Authorize(Roles = "Admin, Funcionario")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _dbContext.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _dbContext.Jogos.FindAsync(id);
            if (jogo == null)
            {
                return NotFound();
            }
            ViewData["IdCategoria"] = new SelectList(_dbContext.Categoria, "Id", "Id", jogo.IdCategoria);
            return View(jogo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, JogoViewModel jogo)
        {
            if (id != jogo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Update(jogo);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogoExists(jogo.Id))
                    {
                        return NotFound();
                    }

GoldenGames.Web/GoldenGames/Views/InfoProduct/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model GoldenGames.Areas.Admin.ViewModels.JogoViewModel

@using GoldenGames.Areas.Admin.ViewModels

@{
    ViewData["Title"] = "Create";

    var categorias = (List<Categorium>)ViewData["Categorias"];
    var consolas = (List<Consola>)ViewData["Consolas"];
}

<body class="aboutCreateProduct">
    <section class="CreateGame">

        <div class="row">
            <div class="AboutGame col-md-4">
                <h1>Create Jogo</h1>
                <hr />
                
                <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                
                <div class="form-group">
                    <label asp-for="IdCategoria" class="control-label"></label>
                    <select asp-for="IdCategoria" class ="form-control">    
                        <!-- Ciclo que mostre todas as categorias que existem na base de dados-->
                        @foreach(var categoria in @categorias)
                        {
                            <option value="@categoria.Id">@categoria.Nome</option>
                        }
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="IdConsola" class="control-label"></label>
                    <select asp-for="IdConsola" class ="form-control">
                        @foreach(var consola in @consolas)
                        {
                            <option value="@consola.Id">@consola.Nome</option>
                        }
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descricao" class="control-label"></label>
                    <input asp-for="Descricao" class="form-control" />
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Produtora" class="control-label"></label>
                    <input asp-for="Produtora" class="form-control" />
                    <span asp-validation-for="Produtora" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label asp-for="Preco" class="control-label"></label>
                    <input asp-for="Preco" class="form-control" />
                    <span asp-validation-for="Preco" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label"> Anexar imagem de capa do jogo (.png, .jpg, .jpeg).</label>
                    <input type="file" accept=".png,.jpg,.jpeg" name="UploadedImage" class="form-control" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
                </form>
            
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </section>
</body>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoldenGames.Web/GoldenGames/Views/InfoProduct/CreateReview.cshtml
@model GoldenGames.Models.Review

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="InfoProduct" asp-action="CreateReview" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="GameId" value="@Model.GameId" />
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Review" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GoldenGames.Web/GoldenGames/Views/InfoProduct/Delete.cshtml
@model GoldenGames.Models.Jogo

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/_ViewImports.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jogo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produtora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produtora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCategoriaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCategoriaNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GoldenGames.Web/GoldenGames/Views/InfoProduct/Details.cshtml
@model GoldenGames.Models.Jogo

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/_ViewImports.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Jogo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produtora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produtora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GoldenGames.Web/GoldenGames/Views/InfoProduct/Edit.cshtml
@model GoldenGames.Models.Jogo

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/_ViewImports.cshtml";
}

<h1>Edit</h1>

<h4>Jogo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdCategoria" class="control-label"></label>
                <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.IdCategoria"></select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Produtora" class="control-label"></label>
                <input asp-for="Produtora" class="form-control" />
                <span asp-validation-for="Produtora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoldenGames.Web/GoldenGames/Views/InfoProduct/Index.cshtml
@using GoldenGames.Areas.Admin.ViewModels
@using GoldenGames.Models
@using Microsoft.AspNetCore.Identity
@model GoldenGames.Models.Jogo

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Detalhes do Jogo";

    List<Jogo> game = (List<Jogo>)ViewData["Jogo"];
}

<body class="bodydetails">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    <div class="card" style="max-width:5000px; background-color:rgb(22,26,30, 0.9); color:white;">
        <div class="row">
            <div class="col-md-6" >
                <img class="rounded mx-auto d-block" src="data:image/*;base64,@(Convert.ToBase64String(ViewBag.Imagem))"/>
      
            </div>
            @foreach(var jogo in @game)
            {
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size:large"></h5>
                        <p style="align-content:center; color:yellow; font-size:large" class="card-text-center">Preço: @jogo.Preco</p>
                        <p style="align-content:center;" class="card-text-center">Produtora: @jogo.Produtora</p>
                        <p style="align-content:center;" class="card-text-center">Categoria: @ViewBag.NomeCategoria</p>
                        <p style="align-content:center;" class="card-text-center">Consola: @ViewBag.NomeConsola</p>

                        <div class="maisbut">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a asp-controller="Cart" asp-action="AddToCart" asp-route-gameid="@jogo.Id" class="btn btn-sm btn-outline-Second">
                                    ADD TO CART
                                </a>
                            }
                        </div>

                        <div class="maisbut">
                            @if (User.IsInRole("Funcionario") || User.IsInRole("Admin"))
                            {
                                <a asp-controller="InfoProduct" asp-action="Edit" asp-route-id="@jogo.Id" class="btn btn-sm btn-outline-Second">
                                    EDIT PRODUCT
                                </a>
                            }
                        </div>
                    </div>
                </div>

                <div class="info">
                    <br />
                    <h1> Informação</h1>
                    <p>@jogo.Descricao</p>
                </div>
            }
        </div>
    </div>

    <!-- The Modal -->
    <div id="myModal" class="modal" style="width:fit-content">
        <!-- Modal content -->
        <div class="modal-content">
            <div class="row">         
                <p>Produto adicionado com sucesso ao seu carrinho de compras</p>

                <div class="col-md-6">
                    <img src="~/Images/1540-1.jpg" class="rounded mx-auto d-block" alt="...">
                </div>

                <div class="col-md-6">
                    <span class="close">&times;</span>
                    <button type="button" style="position: relative; top:300px;" class="btn btn-outline-primary">CONTINUE SHOPPING</button>
                    <button type="button" style="position: relative; top:300px; left: 15px;" class="btn btn-outline-warning">FINISH PURCHASE</button>
                </div>
            </div>
        </div>
    </div>
    @*---------------------------------Review Section-------------------------------------------*@

    <div >
        @if (User.Identity.IsAuthenticated)
        {
            <div id="create-review-form">
                <form>
                    <div class="form-group">
                        <label for="rating">Rating</label>
                        <input type="number" min="0" max="10" class="form-control" id="rating" name="rating" style="width:200px; height:50px;">
                    </div>
                    <div class="form-group">
                        <label for="content">Review</label>
                        <textarea class="form-control" id="content" name="content" style="width:400px; height:200px;"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Create Review</button>
                </form>
            </div>

            @if (ViewData["Reviews"] != null)
            {
                foreach (var review in (IEnumerable<Review>)ViewData["Reviews"])
                {
                    <div class="review">
                        <p>Avaliação: @review.Rating</p>
                        <p>@review.Content</p>
                        <p>By: @review.UserName | Data: @review.CreatedAt</p>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form asp-action="DeleteReview" asp-route-reviewId="@review.Id">
                                <input type="submit" value="Delete Review" class="btn btn-danger" onclick="return confirm('Tem a certeza que quer apagar a review?');" />
                            </form>
                        }
                    </div>
                }
            }

        }
    </div>


    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var form = document.querySelector("#create-review-form form");

            form.addEventListener("submit", function (e) {
                e.preventDefault();

                var gameId = @Model.Id;
                var rating = document.querySelector("#create-review-form #rating").value;
                var content = document.querySelector("#create-review-form #content").value;

                var xhr = new XMLHttpRequest();
                xhr.open("POST", "@Url.Action("CreateReview", "InfoProduct")");
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                        location.reload();
                    }
                };
                xhr.send("gameId=" + gameId + "&rating=" + rating + "&content=" + content);
            });
        });
    </script>

    <script>
        // Get the modal
        var modal = document.getElementById("myModal");

        // Get the button that opens the modal
        var btn = document.getElementById("buttonCart");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks the button, open the modal 
        btn.onclick = function() {
          modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
    </script>

    <script>
        setTimeout(function () {
            var alert = document.querySelector('.alert');
            alert.remove();
        }, 10000);
    </script>
</body>